INSERT INTO productos(nombre, precio, create_at) VALUES('Panasonic', 800, NOW());
INSERT INTO productos(nombre, precio, create_at) VALUES('Sony', 700, NOW());
INSERT INTO productos(nombre, precio, create_at) VALUES('Apple', 1100, NOW());
INSERT INTO productos(nombre, precio, create_at) VALUES('Sony Netbook', 1000, NOW());
INSERT INTO productos(nombre, precio, create_at) VALUES('Hewlett Packard', 550, NOW());
INSERT INTO productos(nombre, precio, create_at) VALUES('Bianchi', 800, NOW());
INSERT INTO productos(nombre, precio, create_at) VALUES('Nike', 125, NOW());
INSERT INTO productos(nombre, precio, create_at) VALUES('Adidas', 185, NOW());
INSERT INTO productos(nombre, precio, create_at) VALUES('Reebok', 145, NOW());
INSERT INTO productos(nombre, precio, create_at) VALUES('Fila', 95, NOW());